## Exercise:Intro to numpy
Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

We want to work with sales data.  However, in order to do so we need sales data.  So let's make some.  We are working with a month's worth of data that is tracked daily.  We will also be tracking jeans, shirts, and apparel separately. 

### Part A

#### Question 1

The general trend is positive, so make three distinct arrays of length 31 each, starting with 5 and going up to 35 for jeans, shirts, and apparel.

In [38]:
import numpy as np

In [39]:
jeans = np.linspace(5,35,31)
jeans.shape

(31,)

In [40]:
shirts = np.linspace(5,35,31)
apparel = np.linspace(5,35,31)

In [41]:
jeans

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35.])

#### Question 2

We also know Saturdays and Sundays have much more sales than the other days.  Add 10 to every 6th and 7th day (assume the first day in the array is a Monday)

**Hint:** Create a mask that is True for sat and sun and False for the other days

In [42]:
# index 0 is Monday, so index 5 and 6 are Saturday and Sunday respectively
# creating a mask
mask = [True if i%7==5 or i%7==6 else False for i in range(len(jeans))]
mask

[False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False]

In [43]:
jeans[mask] += 10
shirts[mask] += 10
apparel[mask] += 10

#### Question 3

No data is pretty.  We will need some noise.  Create a numpy array of random numbers (normal distribution) that has 31 rows and 3 columns
- generate a single noise array of size (31,3) where each column will represent each array you created above


In [44]:
# The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution. 
noise = np.random.randn(31,3)
noise.shape

(31, 3)

#### Question 4

This random data needs to be scaled.  Add 1.5 to the entire array.  Then divide the jeans column by 2 and multiply the apparel column by 2

In [45]:
# I choose the first column for jeans, second column for shirts, and third column for apparel
noise += 1.5
noise[:,0] /= 2
noise[:,2] *= 2

#### Question 5

Check to make sure that you don't have any negative values in the number of units sold.  If you do, set those values equal to zero.

In [46]:
noise_mask = noise<0

In [47]:
# Jeans
noise[noise_mask[:,0]]

array([[-0.03854004,  3.78410073,  4.03140499],
       [-0.16015727,  0.14995934,  3.82281103]])

In [48]:
# Shirts
noise[noise_mask[:,1]]

array([[ 0.52154048, -0.12908804,  0.79696198]])

In [49]:
# Apparel
noise[noise_mask[:,2]]

array([[ 1.24669522,  2.83451506, -0.47129589],
       [ 1.54801439,  1.40771748, -0.85645492]])

In [50]:
noise[noise_mask] = 0
noise

array([[0.04920539, 0.17956147, 5.35939479],
       [0.        , 3.78410073, 4.03140499],
       [1.59194855, 0.10745075, 4.79559549],
       [1.46180838, 0.83456383, 1.52423895],
       [0.69980727, 0.26433764, 5.05966321],
       [0.62971736, 1.28346827, 4.0184245 ],
       [0.96863141, 1.74419332, 4.86506669],
       [1.08325043, 1.0270614 , 6.06117518],
       [0.98662907, 2.36243795, 5.40424279],
       [1.4705419 , 0.6575446 , 6.13443818],
       [1.74026502, 0.48335196, 3.19719329],
       [0.52154048, 0.        , 0.79696198],
       [1.24669522, 2.83451506, 0.        ],
       [1.06935305, 1.38992177, 3.08801434],
       [0.75384361, 2.33787433, 2.8010865 ],
       [1.48076858, 1.99565671, 1.74842934],
       [0.61819411, 0.42500793, 2.5871161 ],
       [0.67445652, 0.44721855, 4.6572097 ],
       [1.7730714 , 0.97054595, 4.84630732],
       [0.4028736 , 0.14587782, 3.88569544],
       [0.46458764, 2.46248235, 2.99719334],
       [0.98572824, 2.33592214, 3.27385145],
       [0.

#### Question 6

Multiply the Noise array and the data arrays(jeans,shirt and apparel)arrays.You should now have an approximation for number of units sold.Unfortunately, they're floats.Convert the values into integers

In [51]:
jeans *= noise[:,0]
shirts *= noise[:,1]
apparel *=noise[:,2] 

In [52]:
jeans= jeans.astype(int)
jeans

array([ 0,  0, 11, 11,  6, 12, 20, 12, 12, 20, 26,  8, 33, 29, 14, 29, 12,
       14, 40, 13, 16, 25,  0, 30, 14, 46, 10, 30, 35, 11, 32])

In [53]:
shirts= shirts.astype(int)
shirts

array([  0,  22,   0,   6,   2,  25,  36,  12,  30,   9,   7,   0,  76,
        38,  44,  39,   8,   9,  22,   4,  86,  60,   4,  62,  18,  42,
       155,  58,  32,  46,  21])

In [54]:
apparel= apparel.astype(int)
apparel

array([ 26,  24,  33,  12,  45,  80, 102,  72,  70,  85,  47,  12,   0,
        86,  53,  34,  54, 102, 111, 132, 104,  85, 103,   9, 155,   0,
       165, 163, 160,  62,  69])

#### Question 7

Finally, these values are in units sold, but not how much money made.  Let's say each apparel was 10 dollars, each shirt was 20, and each pair of jeans were 30.  Multiply each column by the dollar amount earned by Levis.  What was the total amount earned?

In [55]:
jeans *= 30
shirts *= 20
apparel *= 10

In [59]:
# total amount earned
np.sum([jeans,shirts,apparel])
# you can also do (np.sum(jeans)+np.sum(shirts)+np.sum(apparel))

59140

#### Question 8
Concatenate all the three arrays as a single data array

In [71]:
data= np.stack([jeans,shirts,apparel],axis=-1)
data

array([[   0,    0,  260],
       [   0,  440,  240],
       [ 330,    0,  330],
       [ 330,  120,  120],
       [ 180,   40,  450],
       [ 360,  500,  800],
       [ 600,  720, 1020],
       [ 360,  240,  720],
       [ 360,  600,  700],
       [ 600,  180,  850],
       [ 780,  140,  470],
       [ 240,    0,  120],
       [ 990, 1520,    0],
       [ 870,  760,  860],
       [ 420,  880,  530],
       [ 870,  780,  340],
       [ 360,  160,  540],
       [ 420,  180, 1020],
       [1200,  440, 1110],
       [ 390,   80, 1320],
       [ 480, 1720, 1040],
       [ 750, 1200,  850],
       [   0,   80, 1030],
       [ 900, 1240,   90],
       [ 420,  360, 1550],
       [1380,  840,    0],
       [ 300, 3100, 1650],
       [ 900, 1160, 1630],
       [1050,  640, 1600],
       [ 330,  920,  620],
       [ 960,  420,  690]])

### Part B
#### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).
`An identity matrix is a square matrix having 1s on the main diagonal, and 0s everywhere else`

**Hint:** You can also use `np.identity()` function 

In [76]:
arr= np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Question 2
Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

In [80]:
arr1= np.array([[9,8,7],[6,5,4],[3,2,1]])
arr1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

you can also use np.arange()

In [82]:
# np.arange return evenly spaced values within a given interval.
arr1= np.arange(start=9,stop=0,step=-1)
arr1=arr1.reshape(3,3)
arr1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#### Question 3

Interchange both the rows and columns of the given matrix.

**Hint:** make rows as columns and columns as rows


In [83]:
arr1.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

#### Question 4
Add + 1 to all the elements in the matrix created above.

In [84]:
arr1+1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

Similarly you can do operations like scalar substraction, division, multiplication (operating on each element in the matrix)

#### Question 5

Find the mean of all elements in the given matrix arr2.
- create three lists L1,L2,L3 and populate them with [1, 4,9,121,144,169],[16,25,36,196,225,256],[49,64,81,289,324,361] respectively
- create an array using these lists
- find the mean of the array

In [86]:
L1=[1, 4,9,121,144,169]
L2=[16,25,36,196,225,256]
L3=[49,64,81,289,324,361]
arr2=np.array([L1,L2,L3])
arr2

array([[  1,   4,   9, 121, 144, 169],
       [ 16,  25,  36, 196, 225, 256],
       [ 49,  64,  81, 289, 324, 361]])

In [87]:
arr2.mean()

131.66666666666666

#### Question 6
Find the dot product of two arrays created above in question 4 and question 5

In [89]:
arr3= np.dot(arr1,arr2)
arr3

array([[ 480,  684,  936, 4680, 5364, 6096],
       [ 282,  405,  558, 2862, 3285, 3738],
       [  84,  126,  180, 1044, 1206, 1380]])